# Generated by Django 6.0.3 on 2026-03-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(db_index=True, max_length=255)),
                ('bounding_box', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo')),
            ],
        ),
    ]
